# Generated by Django 4.2.7 on 2023-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='0743fa85-2c8b-450b-ba85-4a7b8a5b70b3', max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(default='-1', max_length=255)),
            ],
        ),
    ]
