# Generated by Django 4.2.7 on 2023-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='5c262009-dc8a-47b8-8498-360345c8a1c3', max_length=255),
        ),
    ]
