# Generated by Django 4.2.7 on 2023-11-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0002_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nn_answer',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='014abd4e-a206-4980-9225-c32d0ffb92c6', max_length=255),
        ),
    ]
